spring.application.name=adoptions
#
spring.datasource.url=jdbc:postgresql://localhost/mydatabase
spring.datasource.username=myuser
spring.datasource.password=secret
#
spring.mvc.apiversion.default=1.1
spring.mvc.apiversion.use.header=x-dogs-version
#

spring.modulith.events.republish-outstanding-events-on-restart=true
spring.modulith.events.jdbc.schema-initialization.enabled=true